# Generated by Django 5.0.1 on 2024-01-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='format',
            field=models.CharField(default='jpg', max_length=16),
        ),
    ]
