# Generated by Django 4.1.13 on 2024-03-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_deleted_at_alter_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
